secret:
  socketio: 
  jwt: 
  session: 
  cookie: 
  
aws:
  access_key_id: 
  secret_access_key: 

domain:
  s3: 
  disallow_app:
    - api
    - app 
    - support
    - help
    - blog 
    - admin
    - test
    - dev
    - development
    - stage
    - staging
    - prod
    - production
    - cs
    - customer

policy:
  period:
    seconds_post_read_per_session: 60

request_timeout: 20000